[package]
name = "mockmqttdata"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "0.24.0"
tokio = { version = "1", features = ["full"] }
eframe = "0.24.0"
winapi = { version = "0.3", features = ["winuser", "windef"] }
